insert into rubric_criteria (role, position, name, description, weight) values
('SPM', 1, 'Hands-On Operations Time', 'At least 24 months of personally doing operational work in freight forwarding, customs/CHA, port, 3PL, carrier or supply-chain operations, and can show they understand the integration/data side of it (e.g. carrier or port-system coordination, FMS/TMS migrations, EDI/document data flows). WEAK: under a year of hands-on time, or domain exposure only through building/selling/advising.', 20),
('SPM', 2, 'Built It Unasked, Others Kept Using It', 'At least two self-started tools, processes or frameworks, each with evidence of adoption beyond their own team (other teams, the whole company, or customers), and at least one that became a standing practice that outlasted the initial effort. WEAK: a single example, adoption limited to their own team, or work done because it was assigned.', 25),
('SPM', 3, 'Owned It With No Safety Net', 'Across more than one role or a sustained period, was the sole or most senior owner of a product area, function or account base with nobody above making the calls, including hard trade-off decisions (what to build, stop, or refuse) and accountability for the consequences. Bonus: built or trained a team or set standards others followed. WEAK: senior title but decisions routed through committees, managers or peers; ownership of a slice inside a bigger team.', 35),
('SPM', 4, 'Writes Down What Failed', 'Repeated pattern (two or more instances) of killing work on evidence, running post-mortems, or documenting root causes, where the learning was turned into a process or rule that others now follow. WEAK: one isolated instance, or no changed process afterwards.', 20),
('PM', 1, 'Hands-On Operations Time', 'Has personally done day-to-day operational work in freight forwarding, customs/CHA, port, 3PL, carrier or supply-chain operations (e.g. prepared shipping documents, coordinated carriers, resolved shipment exceptions, handled forwarder accounts) for at least 12 months, with specifics such as volumes, document types, or named parties. WEAK: only built software for, sold to, or advised logistics companies without doing the operational work; or logistics appears only as a keyword/skill list.', 30),
('PM', 2, 'Built It Unasked, Others Kept Using It', 'Names at least one tool, process, template or framework they started without being assigned, AND states that people beyond their own immediate team adopted or kept using it (who/how many/how long). Two or more such examples = top score. WEAK: improvements that were part of the assigned job, or adoption by only their own small team, or no evidence anyone used it.', 30),
('PM', 3, 'Owned It With No Safety Net', 'Explicitly owned a product, account, process or function as the only or most senior person (sole owner, "no manager/layer above", no escalations) and made the calls themselves. WEAK: worked as one member of a larger team, presented to seniors for approval, or ownership is implied only by a title.', 20),
('PM', 4, 'Writes Down What Failed', 'Shows at least one case where they killed a feature/initiative, ran a post-mortem, or documented a root cause of a loss or outage, and something changed afterwards (a process, a decision, a shared write-up). WEAK: only success stories; failures absent or mentioned without any consequence.', 20)
on conflict (role, name) do update set position=excluded.position, description=excluded.description, weight=excluded.weight;